- hosts: localhost
  become: yes
  tasks:
    - name: Unstack OpenStack
      shell: ./unstack.sh
      args:
        chdir: /opt/devstack

    - name: Clean DevStack
      shell: ./clean.sh
      args:
        chdir: /opt/devstack

    - name: Remove DevStack directory
      file:
        path: /opt/devstack
        state: absent
